import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "../context/CartContext"; // <--- DIUBAH

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Toko Online Next.js",
  description: "Generated by create next app",
};

// app/layout.tsx

// ... import ...

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Tambahkan suppressHydrationWarning di sini */}
      <body suppressHydrationWarning className={inter.className}>
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}